name: JS Docs
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./source/js/buttons.js
        recurse: true
        output_dir: ./out

