name: JS Docs
on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '**'
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run doc
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: source/js
          recurse: true
          output_dir: out

