name: JS Docs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: cse110-w21-group32/source/js/

        output_dir: ./out
        recurse: true
