name: JS Docs
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./out

